# Note

<font color='red'>All the index in this notebook starts with 1 (Julia/Matlab convention)</font>

The stabilizer state can be written as
$$|\psi\rangle = \sum_{\vec{v},h}\mathbb{i}^{\vec{L}\cdot[\vec{v};h]}(-1)^{[\vec{v};h]^{T}\cdot \textbf{Q}\cdot [\vec{v};h]}\delta\left(\textbf{P}\cdot[\vec{v};1;h]=0\text{ mod 2}\right)\tag{1}$$

- $\vec{v}=(v_1,v_2,\dots,v_n)$ denotes $n$ visible binary variable. $h$ is a binary scalar, denoting hidden variable. In the following, we will see we have at most one hidden variable at any given time.
- $\vec{L}$ is a (n+1)-by-1 integer vector (mod 4). The first $n$ elements are the coefficient for visible variable. And the last element is the coefficient for the hidden variable.
- $\textbf{Q}$ is a (n+1)-by-(n+1) upper triangular integer matrix (mod 2), with zero diagonal elements. It denotes the quadratic terms, such as $Q_{ij}v_iv_j$
- $\textbf{P}$ is a (m)-by-(n+2) integer matrix (mod 2), and $0\leq m \leq n$. Each row is a constraints for $\vec{v}$ and $h$. The first $n$ elements are coefficient for visible variable. It follows a coefficient for constant bias 1 and a coefficient for hidden variable.

At any given time, after we sum over the hidden variable, the stabilizer state can be written as Eq.(1), where the last element of $\vec{L}$ is 0, the last column of $\textbf{Q}$ is zero, and the last column of $\textbf{P}$ is 0.

For example, the all-up state is a stabilizer state with 
$$\vec{L}=(0,0,\cdots,0|0)\tag{2}$$
$$\textbf{Q}=\textbf{0}\tag{3}$$
$$\textbf{P}=[\textbf{1}|\vec{0}|\vec{0}]$$

where $\textbf{1}$ is the identity matrix, and $\vec{0}$ is zero vector.

Add projector $\dfrac{1\pm P}{2}$ to the state: $P$ is a Pauli operator.

- If the sign is "-", add $(-1)^h$

- If $P_i=Z_i$: add $(-1)^{v_i h}$ $\rightarrow$ $Q_{i,h}=Q_{i,h}+1 (\text{mod}2)$

- If $P_i=X_i$: $v_i\rightarrow v_i+h(\text{mod 2})$. It means:
    - Changes induced by linear term $\mathbb{i}^{L_i v_i+L_i h}(-1)^{L_i v_i h}$: (1). $L_h=L_h+L_i(\text{mod 4})$ (2).$Q_{i,h}=Q_{i,h}+L_i(\text{mod 2})$
    - Changes induced by quadratic term $(-1)^{Q_{i,j}v_i v_j}(-1)^{Q_{i,j}v_j h}$: (j>i) For $Q_{i,j}\neq 0$, $Q_{j,h}=Q_{j,h}+Q_{i,j}\text{(mod 2)}$.; (j<i) For $Q_{j,i}\neq 0$, $Q_{j,h}=Q_{j,h}+Q_{j,i}\text{(mod 2)}$

- If $P_i=Y_i$: First change $v_i\rightarrow v_i+h(\text{mod 2})$, then add $\mathbb{i}^{3h}(-1)^{v_i h}$:
    - Changes induced by linear term $\mathbb{i}^{L_i v_i+L_i h}(-1)^{L_i v_i h}$: (1). $L_h=L_h+L_i(\text{mod 4})$ (2).$Q_{i,h}=Q_{i,h}+L_i(\text{mod 2})$
    - Changes induced by quadratic term $(-1)^{Q_{i,j}v_i v_j}(-1)^{Q_{i,j}v_j h}$: (j>i) For $Q_{i,j}\neq 0$, $Q_{j,h}=Q_{j,h}+Q_{i,j}\text{(mod 2)}$.; (j<i) For $Q_{j,i}\neq 0$, $Q_{j,h}=Q_{j,h}+Q_{j,i}\text{(mod 2)}$
    - $L_h=L_h+3(\text{mod 4})$, $Q_{i,h}=Q_{i,h}+1(\text{mod 2})$

The crucial part is that we only have $\textbf{one}$ hidden variable $h$ after adding a Pauli projector.

Integrating over $h$:

Check if $\textbf{P}[:,-1]$ contains non-zero elements (constraints involve hidden variable):
- If there are more than 1 non-zero elements:
    - Find first row ($k$) where $\textbf{P}[k,-1]\neq 0$, and add $\textbf{P}[j,:]=\textbf{P}[j,:]+\textbf{P}[k,:](\text{mod }2)$ for $\textbf{P}[j,-1]\neq 1$
    - replace $h = \textbf{P}[k,:-1]\cdot \vec{v}$:
        - *[Linear term]*: If $L[-1]\neq 0$ (exist non-zero coefficient for hidden variable): For $l$ in 1:n, if $P[k,l]\neq 0$, $L[l]=L[l]+(1+2*P[k,-2])*L[-1]*P[k,l](\text{mod 4})$; quadratic from linear: For $p$ in 1:n, For $q$ in (p+1):n, If (P[k,p]$\neq$0)&(P[k,q]$\neq$0), then $Q[p,q]=Q[p,q]+L[-1](\text{mod 2})$
        - *[Quadratic term]*: For $l$ in 1:n, if $Q[l,-1]\neq 0$, there is interaction between $v_l$ and $h$: if $P[k,-2]\neq 0$, $L[l]=L[l]+2\text{(mod 4)}$, then for $m$ in 1:n, if $P[k,m]\neq 0$: if $m=l$, $L[l]=L[l]+2\text{(mod 4)}$, else $Q[l,m]=Q[l,m]+1(\text{mod 2})$(m>l)
    - **Reset:**, delete $\textbf{P}[k,:]$, set $L[-1]=0$, set $Q[:,-1]=0$

Else, it means $\textbf{P}[:,-1]=0$  (constraints do not involve hidden variable): we only need to sum over $h$ in linear and quadratic terms

- If $L[-1]=0$ (coefficient of $h$ in linear term is 0):
    $$\sum_{h}(-1)^{h L_p}=2 \delta(L_p \text{ mod 2})$$
    $L_p=Q[1:n,-1]$. If $[L_p,0,0]$ is independent of $\textbf{P}$, add $[L_p,0,0]$ to $\textbf{P}$. Otherwise, the constraints is already in $\textbf{P}$
    
    **Reset:** set $Q[:,-1]=0$

- If $L[-1]=1$
    $$\sum_h (-1)^{h L_p}\mathbb{i}^{h}=(1+\mathbb{i})\mathbb{i}^{3L_p^2}$$
    $L_p=Q[1:n,-1]$. 
    
    *[update linear term]*: For $l$ in 1:n, if $Q[l,-1]\neq 0$, $L[l]=L[l]+3*Q[l,-1]^2=L[l]+3Q[l,-1](\text{mod 4})$.
    
    *[update quadratic term]*: For $l$ in 1:n & For $m$ in ($l$+1):n. If $(Q[l,-1]\neq 0)\&(Q[m,-1]\neq 0)$, $Q[l,m]=Q[l,m]+3Q[l,-1]Q[m,-1](\text{mod 2})$
    
    **Reset:** set $L[-1]=0$, set $Q[:,-1]=0$

- If $L[-1]=2$
    $$\sum_h (-1)^{h L_p}\mathbb{i}^{2h}=2\delta(L_p+1 \text{mod 2})$$
    $L_p=Q[1:n,-1]$. If $[L_p,1,0]$ is independent of $\textbf{P}$, add $[L_p,1,0]$ to $\textbf{P}$. Otherwise, the constraints is already in $\textbf{P}$
    
    **Reset:** set $L[-1]=0$, set $Q[:,-1]=0$

- If $L[-1]=3$
    $$\sum_h (-1)^{h L_p}\mathbb{i}^{3h}=(1-\mathbb{i})\mathbb{i}^{L_p^2}$$
    $L_p = Q[1:n, -1]$.
    
    *[update linear term]:* For $l$ in 1:n, if $Q[l,-1]\neq 0$, $L[l]=L[l]+Q[l,-1]^2=L[l]+Q[l,-1](\text{mod 4})$.
    
    *[update quadratic term]:* For $l$ in 1:n & For m in $l+1$:n: If $(Q[l,-1]\neq)\&(Q[m,-1]\neq 0)$, $Q[l,m]=Q[l,m]+Q[l,-1]Q[m,-1](\text{mod 2})$
    
    **Reset:** set $L[-1]=0$, set $Q[:,-1]=0$

# Implementation

In [1]:
from context import *

In [2]:
from numba import njit

In [925]:
rho = stabilizer.stabilizer_state("ZZ","-YY")

In [926]:
rho.density_matrix

0.25000 II -0.25000 YY +0.25000 ZZ +0.25000 XX

In [927]:
rho.to_qutip()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

In [38]:
rho.ps

array([0, 2, 0, 0])

In [39]:
rho.density_matrix

0.25000 II -0.25000 YY +0.25000 XX +0.25000 ZZ

In [40]:
stabilizer.ghz_state(2).density_matrix

0.25000 II +0.25000 XX +0.25000 ZZ -0.25000 YY

In [88]:
for i in range(1,4):
    print(i)

1
2
3


In [267]:
@njit
def z2rank(mat):
    '''Calculate Z2 rank of a binary matrix.

    Parameters:
    mat: int matrix - input binary matrix.
        caller must ensure that mat contains only 0 and 1.
        mat is destroyed upon output! 

    Returns:
    r: int - rank of the matrix under Z2 algebra.'''
    nr, nc = mat.shape # get num of rows and cols
    r = 0 # current row index
    for i in range(nc): # run through cols
        if r == nr: # row exhausted first
            return r # row rank is full, early return
        if mat[r, i] == 0: # need to find pivot
            found = False # set a flag
            for k in range(r + 1, nr):
                if mat[k, i]: # mat[k, i] nonzero
                    found = True # pivot found in k
                    break
            if found: # if pivot found in k
                # swap rows r, k
                for j in range(i, nc):
                    tmp = mat[k,j]
                    mat[k,j] = mat[r, j]
                    mat[r,j] = tmp
            else: # if pivot not found
                continue # done with this col
        # pivot has moved to mat[r, i], perform GE
        for j in range(r + 1, nr):
            if mat[j, i]: # mat[j, i] nonzero
                mat[j, i:] = (mat[j, i:] + mat[r, i:])%2
        r = r + 1 # rank inc
    # col exhausted, last nonvanishing row indexed by r
    return r

In [956]:
@njit
def update_LQP(g, p, L, Q, P):
    '''
    !!! This is an in-place function
    g is array of pauli string (mod 2)
    p is imag phase
    L is (n+1) vector (mod 4)
    Q is (n+1)-(n+1) matrix (mod 2)
    P is m-(n+2) matrix (mod 2)
    '''
    N = g.shape[0]//2
    if p == 2: # minus pauli
        L[-1] = (L[-1]+2)%4
    for i in range(N):
        if np.sum(g[2*i:2*i+2]==np.array([0,1]))==2: #Z_i 
            Q[i,-1]=(Q[i,-1]+1)%2
        elif np.sum(g[2*i:2*i+2]==np.array([1,0]))==2: #X_i 
            L[-1] = (L[-1]+L[i])%4
            Q[i,-1]=(Q[i,-1]+L[i])%2
            for j in range(i+1,N):
                if Q[i,j]!=0:
                    Q[j,-1]=(Q[j,-1]+Q[i,j])%2
            for j in range(i):
                if Q[j,i]!=0:
                    Q[j,-1]=(Q[j,-1]+Q[j,i])%2
            P[:,-1] = (P[:,-1]+P[:,i])%2
        elif np.sum(g[2*i:2*i+2]==np.array([1,1]))==2: #Y_i 
            L[-1]=(L[-1]+L[i])%4
            Q[i,-1]=(Q[i,-1]+L[i])%2
            for j in range(i+1,N):
                if Q[i,j]!=0:
                    Q[j,-1]=(Q[j,-1]+Q[i,j])%2
            for j in range(i):
                if Q[j,i]!=0:
                    Q[j,-1]=(Q[j,-1]+Q[j,i])%2
            L[-1]=(L[-1]+3)%4
            Q[i,-1]=(Q[i,-1]+1)%2
            P[:,-1]=(P[:,-1]+P[:,i])%2
    return L, Q, P

In [957]:
@njit
def numbda_vstack(a,b):
    '''
    Due to numba compilation, this function only supports when inputs are matrices.
    '''
    print("a shape:", a.shape)
    print("b shape:", b.shape)
    assert a.shape[1]==b.shape[1]
    comb = np.zeros((a.shape[0]+b.shape[0],a.shape[1]))
    comb[:a.shape[0],:]=a
    comb[a.shape[0]:,:]=b
    return comb

In [958]:
# @njit
def integrate_hidden(L,Q,P):
    '''
    !!! This is an in-place function
    L is (n+1) vector (mod 4)
    Q is (n+1)-(n+1) matrix (mod 2)
    P is m-(n+2) matrix (mod 2)
    '''
    N = Q.shape[0]-1
    if np.sum(P[:,-1])>0 : # constraints contain hidden variable
        k = 0
        while P[k,-1]==0:
            k=k+1
        # get first row (k) involve hidden contraints
        for j in range(k+1,P.shape[0]):
            if P[j,-1]!=0:
                P[j,:]=(P[j,:]+P[k,:])%2
        # Replace h=P[k,:-1]*vec{v}
        # Linear term-linear:
        if L[-1]!=0: #has nonzero coefficient for hidden in linear term
            for l in range(N):
                if P[k,l]!=0:
                    L[l]=(L[l]+(1+2*P[k,-2])*L[-1]*P[k,l])%4
        # Linear term-quadratic:
        for p in range(N):
            for q in range(p+1,N):
                if (P[k,p]!=0)&(P[k,q]!=0):
                    Q[p,q]=(Q[p,q]+L[-1])%2
        # Quadratic term:
        for l in range(N):
            if Q[l,-1]!=0: # there is v_l*h term
                if P[k,-2]!=0: #there is bias term in constraints
                    L[l]=(L[l]+2)%4
                for m in range(N):
                    if P[k,m]!=0:
                        if m==l:
                            L[l]=(L[l]+2)%4
                        elif m>l:
                            Q[l,m]=(Q[l,m]+1)%2
                        else: #l<m
                            Q[m,l]=(Q[m,l]+1)%2
        # Reset:
        P = np.delete(P,k,0) # this is not supported by numba and not in-place change
        L[-1]=0
        Q[:,-1]=np.zeros(N+1).astype(int)
    else: # constraints doesn't contain hidden variable
        if L[-1]==0: #coeff of h in linear term is zero
            newP = np.zeros(N+2).astype(int)
            newP[0:N]=Q[0:N,-1]
            if np.sum(P[0,:])==0:# No contraints yet!
                P[0,:]=newP
            else:
                current_rank = P.shape[0]
                new_rank = z2rank(numbda_vstack(P,newP.reshape(1,-1)))
                if new_rank>current_rank: # new constraints
                    P = numbda_vstack(P,newP.reshape(1,-1))
            # Reset
            Q[:,-1]=np.zeros(N+1).astype(int)
        elif L[-1]==1: 
            # update linear term
            for l in range(N):
                if Q[l,-1]!=0:
                    L[l]=(L[l]+3*Q[l,-1])%4
            # update quadratic term
            for l in range(N):
                for m in range(l+1,N):
                    if (Q[l,-1]!=0)&(Q[m,-1]!=0):
                        Q[l,m]=(Q[l,m]+3*Q[l,-1]*Q[m,-1])%2
            # Reset
            L[-1]=0
            Q[:,-1]=np.zeros(N+1).astype(int)
        elif L[-1]==2:
            newP = np.zeros(N+2).astype(int)
            newP[0:N]=Q[0:N,-1]
            newP[N]=1
            if np.sum(P[0,:])==0:# No contraints yet!
                P[0,:]=newP
            else:
                current_rank = P.shape[0]
                new_rank = z2rank(numbda_vstack(P,newP.reshape(1,-1)))
                if new_rank>current_rank: # new constraints
                    P = numbda_vstack(P,newP.reshape(1,-1))
            # Reset
            L[-1]=0
            Q[:,-1]=np.zeros(N+1).astype(int)
        else:
            assert L[-1]==3
            # update linear term
            for l in range(N):
                if Q[l,-1]!=0:
                    L[l]=(L[l]+Q[l,-1])%4
            # update quadratic term
            for l in range(N):
                for m in range(l+1,N):
                    if (Q[l,-1]!=0)&(Q[m,-1]!=0):
                        Q[l,m]=(Q[l,m]+Q[l,-1]*Q[m,-1])%2
            # Reset
            L[-1]=0
            Q[:,-1]=np.zeros(N+1).astype(int)  
    return L, Q, P

## Test

In [996]:
L = np.array([0,0,0,0]).astype(int)

In [997]:
Q = np.zeros((4,4)).astype(int)

In [998]:
P = np.array([[0,0,0,0,0]])

In [999]:
L, Q, P = update_LQP(paulialg.pauli("YZX").g,2,L,Q,P)

In [1000]:
L, Q, P = integrate_hidden(L,Q,P)

In [1001]:
L, Q, P = update_LQP(paulialg.pauli("IIX").g,0,L,Q,P)

In [1002]:
L, Q, P = integrate_hidden(L,Q,P)

In [1003]:
L, Q, P = update_LQP(paulialg.pauli("IZI").g,0,L,Q,P)

In [1004]:
L, Q, P = integrate_hidden(L,Q,P)

In [1005]:
print("L: ",L)
print("Q: ",Q)
print("P: ",P)

L:  [3 3 0 0]
Q:  [[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
P:  [[0 1 0 0 0]]


In [1010]:
state = np.matmul(stabilizer.stabilizer_state("-YZX","IIX","IZI").to_qutip().full(),np.ones(8))

In [1011]:
state = state*(np.conj(state[0]))
print(state/state[0])

[1.+0.j 1.+0.j 0.+0.j 0.+0.j 0.-1.j 0.-1.j 0.+0.j 0.+0.j]


In [995]:
stabilizer.random_clifford_state(3)

StabilizerState(
   +YZX
   +IIX
   +IZI)

# Develop

In [229]:
@njit
def delete_workaround(arr, num):
    mask = np.zeros(arr.shape[0], dtype=np.int64) == 0
    print(mask)
    mask[np.where(arr == num)[0]] = False
    return arr[mask]

In [230]:
delete_workaround(np.array([[1,2,3],[4,5,6],[7,8,9]]),3)

[ True  True  True]


array([[4, 5, 6],
       [7, 8, 9]])

In [269]:
np.vstack([np.array([[1,2,3],[3,3,3]]),np.array([3,2,3])])

array([[1, 2, 3],
       [3, 3, 3],
       [3, 2, 3]])

In [84]:
a = np.random.rand(5,5)
print(a)

[[0.41629642 0.14370698 0.66743301 0.58196928 0.83077058]
 [0.02966384 0.24539921 0.26387363 0.55925178 0.66816607]
 [0.48609719 0.76985879 0.1477727  0.76039783 0.7710577 ]
 [0.44670952 0.36719223 0.54222802 0.48359624 0.93018027]
 [0.25058035 0.57952452 0.39279824 0.74382935 0.86542772]]


In [87]:
a[1,2:4]

array([0.26387363, 0.55925178])

In [72]:
@njit
def test(a):
    if np.sum(a==np.array([0,0]))==2:
        return print("True")
    else:
        return print("False")


In [75]:
test(np.array([1,1]))

False


In [49]:
update_LQP(0,2,L,L,L)

(array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1]))