In [1]:
import sys
sys.path.insert(0, '..')
import numpy as np
import matplotlib.pyplot as plt
import pyclifford as pc
import time

In [14]:
a =pc.random_clifford_state(3)

In [15]:
a

StabilizerState(
   +YII
   +IXY
   +IYZ)

In [16]:
a.canonicalization()

StabilizerState(
   +YII
   +IXY
   -IZX)

In [17]:
a.gs

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [18]:
tmp = a.gs.copy()

In [19]:
tmp

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [21]:
np.delete(tmp, [0,1], axis=0)

array([[0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]])