In [3]:
import sys
sys.path.insert(0, '..')
import numpy as np
import matplotlib.pyplot as plt
import pyclifford as pc
import time

In [5]:
a =pc.random_clifford_state(3)

In [6]:
a

StabilizerState(
   +XYI
   +XII
   +IYZ)

In [7]:
a.gs

array([[1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0]])

In [8]:
pc.utils.rref_canonicalization(a.gs, a.ps)

(array([[1, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0, 1],
        [0, 1, 0, 1, 0, 0],
        [1, 0, 1, 1, 1, 0]]),
 array([0, 0, 0, 0, 0, 0]))