In [1]:
# will autoupdate any of the packages imported:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [7]:
import sys
sys.path.insert(0, '..')
import numpy as np
import matplotlib.pyplot as plt
import pyclifford as pc
import time

In [35]:
a =pc.ghz_state(3)

In [36]:
a

StabilizerState(
   +ZZI
   +IZZ
   +XXX)

In [37]:
a.set_r(1)

StabilizerState(
   +IZZ
   +XXX)

In [38]:
a.canonicalization()

StabilizerState(
   +XXX
   +IZZ)

In [44]:
print(a.to_qutip())

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.25 0.   0.   0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.25 0.   0.   0.  ]
 [0.   0.   0.   0.25 0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.25 0.   0.   0.   0.   0.   0.   0.25]]


In [25]:
a.swap(0,1)
a.swap(1,2)

StabilizerState(
   +ZZI
   +XXX)

In [24]:
a.entropy([0])

0

In [18]:
a.entropy([0,1,2])

1

In [65]:
print(a.to_qutip())

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.125 0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.125 0.    0.    0.    0.    0.125 0.   ]
 [0.    0.    0.125 0.    0.    0.125 0.    0.   ]
 [0.    0.    0.    0.125 0.125 0.    0.    0.   ]
 [0.    0.    0.    0.125 0.125 0.    0.    0.   ]
 [0.    0.    0.125 0.    0.    0.125 0.    0.   ]
 [0.    0.125 0.    0.    0.    0.    0.125 0.   ]
 [0.125 0.    0.    0.    0.    0.    0.    0.125]]


In [18]:
tmp = a.gs.copy()

In [19]:
tmp

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [21]:
np.delete(tmp, [0,1], axis=0)

array([[0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [37]:
pc.utils.mask([0,2],3)

array([ True, False,  True])