In [2]:
import pyclifford as pc
import numpy as np

## Construct Clifford Maps

`identity_map(N)` constructs an identity Clifford map on $N$ qubits.

In [3]:
pc.identity_map(4)

CliffordMap(
  X0-> +XIII
  Z0-> +ZIII
  X1-> +IXII
  Z1-> +IZII
  X2-> +IIXI
  Z2-> +IIZI
  X3-> +IIIX
  Z3-> +IIIZ)

`random_pauli_map(N)` samples a random Clifford map made of random single-qubit Clifford gates on $N$ qubits, i.e. $U=\prod_i U_i\in\mathrm{Cl}(2)^N$. Each realization specifies a random local Pauli basis.

In [4]:
pc.random_pauli_map(4)

CliffordMap(
  X0-> +ZIII
  Z0-> -YIII
  X1-> +IXII
  Z1-> +IYII
  X2-> +IIZI
  Z2-> +IIXI
  X3-> +IIIZ
  Z3-> +IIIY)

`random_clifford_map(N)` samples a globally random Clifford map on $N$ qubits, i.e. $U\in\mathrm{Cl}(2^N)$. Each realization specifies a random global stabilizer basis.

In [6]:
pc.random_clifford_map(4)

CliffordMap(
  X0-> -ZXIZ
  Z0-> -XIYI
  X1-> +XXYX
  Z1-> -IXYZ
  X2-> -YXZX
  Z2-> -IIYI
  X3-> -IXII
  Z3-> +IZIY)

`clifford_rotation_map(N)` constructs a Clifford map based for a Clifford rotation given its generator.

In [8]:
pc.clifford_rotation_map('-XXYZ')

CliffordMap(
  X0-> +XIII
  Z0-> +YXYZ
  X1-> +IXII
  Z1-> +XYYZ
  X2-> +XXZZ
  Z2-> -XXXZ
  X3-> -XXYY
  Z3-> +IIIZ)

## Construct Stabilizer States

`maximally_mixed_state(N)` constructs a $N$-qubit maximally mixed state (by setting the density matrix to full rank).
$$\rho=2^{-N}\mathbb{1}.$$

In [9]:
pc.maximally_mixed_state(4)

StabilizerState()

`zero_state(N)` constructs a $N$-qubit all-zero state 
$$\rho=|0\cdots0\rangle\langle 0\cdots0|=\prod_{i}\frac{1+Z_i}{2}.$$

In [10]:
pc.zero_state(4)

StabilizerState(
   +ZIII
   +IZII
   +IIZI
   +IIIZ)

`one_state(N)` constructs a $N$-qubit all-one state 
$$\rho=|1\cdots1\rangle\langle 1\cdots1|=\prod_{i}\frac{1-Z_i}{2}.$$

In [11]:
pc.one_state(4)

StabilizerState(
   -ZIII
   -IZII
   -IIZI
   -IIIZ)

`ghz_state(N)` constructs a $N$-qubit GHZ state
$$\rho = |\Psi\rangle\langle\Psi|, \qquad \text{with }|\Psi\rangle=\frac{1}{\sqrt{2}}(|0\cdots0\rangle+|1\cdots1\rangle).$$

In [12]:
pc.ghz_state(4)

StabilizerState(
   +ZZII
   +IZZI
   +IIZZ
   +XXXX)

`random_pauli_map(N)` samples a $N$ qubit random Pauli state.
$$\rho=U|0\cdots0\rangle\langle 0\cdots0|U^\dagger,\qquad\text{with }U\in \mathrm{Cl}(2)^N.$$

In [13]:
pc.random_pauli_map(4)

CliffordMap(
  X0-> -ZIII
  Z0-> +YIII
  X1-> -IXII
  Z1-> -IZII
  X2-> +IIZI
  Z2-> +IIXI
  X3-> -IIIZ
  Z3-> -IIIY)

`random_clifford_map(N)` samples a $N$ qubit random Clifford (random stabilizer) state.
$$\rho=U|0\cdots0\rangle\langle 0\cdots0|U^\dagger,\qquad\text{with }U\in \mathrm{Cl}(2^N).$$

In [14]:
pc.random_clifford_state(4)

StabilizerState(
   +ZZYI
   +YYYX
   +XXYX
   +ZZIX)

`stabilizer_state(...)` is a universal constructor of stabilizer state by specifying all stabilizers.

In [16]:
pc.stabilizer_state('XXY','ZZI','IZZ')

StabilizerState(
   +XXY
   +ZZI
   +IZZ)

## Construct Stabilizer States by Checker Matrix

The user can also construct stabilizer state by low-level constructor `StabilizerState(gs, ps, r=0)`:

**Parameters**
- `gs: int (2*N, 2*N)`: strings of Pauli operators in the stabilizer tableau.
- `ps: int (2*N)`: phase indicators (should only be 0 or 2).
- `r:  int`: number of logical qubits (log2 rank of density matrix)'''

**Returns**
- Object of `StabilizerState`

In [17]:
tmp_state = pc.random_clifford_state(3)
print(tmp_state)

StabilizerState(
   +IXI
   +YXI
   +YIY)


In [18]:
gs = tmp_state.gs
ps = tmp_state.ps
pc.StabilizerState(gs=gs,ps=ps)

StabilizerState(
   +IXI
   +YXI
   +YIY)

A hack to inspect the full stabilizer tableau is by converting `StabilizerState` to `PauliList` by

In [19]:
pc.stabilizer_state('XXY','ZZI','IZZ')[:]

 +XXY
 +ZZI
 +IZZ
 +ZII
 +ZXX
 +ZIX

## State-Map convertion

Stabilizer states and Clifford maps can be mapped to each other.

In [20]:
rho = pc.stabilizer_state('XXX','ZZI','IZZ')
print("quantum state: \n", rho)

quantum state: 
 StabilizerState(
   +XXX
   +ZZI
   +IZZ)


In [21]:
rho.to_map()

CliffordMap(
  X0-> +ZII
  Z0-> +XXX
  X1-> +IXX
  Z1-> +ZZI
  X2-> +IIX
  Z2-> +IZZ)

And Clifford map can be converted back to the stabilizer state.

In [22]:
rho.to_map().to_state()

StabilizerState(
   +XXX
   +ZZI
   +IZZ)

* `.to_map()` and `.to_state()` will make **new copies** of Pauli string data in the memory.

<div class="alert alert-block alert-danger">
The information about the rank of the density matrix is lost in the Clifford map, so the back conversion will result in a zero rank stabilizer state.
</div>

## Methods for Clifford maps

### Embedding small Clifford map into larger map

`.embed(small_map, mask)` provides the method to embed a smaller Clifford map on a subset of qubits to the current Clifford map. This is a **in-place** operation. The Clifford map object that provide this method will get modified under the embedding.

**Parameters:**
* `small_map` is a `CliffordMap` object supported on a subset of qubits.
* `mask` is a boolean array specifying the subset of qubits.

In [24]:
cmap = pc.identity_map(6)
cmap

CliffordMap(
  X0-> +XIIIII
  Z0-> +ZIIIII
  X1-> +IXIIII
  Z1-> +IZIIII
  X2-> +IIXIII
  Z2-> +IIZIII
  X3-> +IIIXII
  Z3-> +IIIZII
  X4-> +IIIIXI
  Z4-> +IIIIZI
  X5-> +IIIIIX
  Z5-> +IIIIIZ)

In [25]:
cmap.embed(pc.random_clifford_map(3), np.array([True,False,False,True,True,False]))

CliffordMap(
  X0-> -XIIXYI
  Z0-> -YIIZZI
  X1-> +IXIIII
  Z1-> +IZIIII
  X2-> +IIXIII
  Z2-> +IIZIII
  X3-> -YIIXXI
  Z3-> -XIIXII
  X4-> -XIIIYI
  Z4-> +ZIIYII
  X5-> +IIIIIX
  Z5-> +IIIIIZ)

### Map Composition

`.compose(other)` returns the composition of the current Clifford map with another Clifford map. This will return a new Clifford map without modifying either of the input maps. The Clifford map object which initiates this method will be the preceeding map in the composition. 

**Parameters:**
* `other` - another `CliffordMap`.

In [27]:
cmap.compose(pc.random_clifford_map(6))

CliffordMap(
  X0-> +YZYIZZ
  Z0-> -YXIXYX
  X1-> -XXYXIZ
  Z1-> -XZIZIY
  X2-> -IYYYYI
  Z2-> -IIIZYY
  X3-> -XIYYIX
  Z3-> +IZYZII
  X4-> +ZZZXXY
  Z4-> -YXIXIX
  X5-> +IIXXIX
  Z5-> +YXYXIX)

### Map Inversion

`.inverse()` returns the inverse of the current Clifford map. This will return a new Clifford map withoutt modifying the original map. The inverse map is such that its composition with the original map must be identity

In [28]:
cmap = pc.clifford_rotation_map('Y')
cmap

CliffordMap(
  X0-> -Z
  Z0-> +X)

In [29]:
cmap.inverse()

CliffordMap(
  X0-> +Z
  Z0-> -X)

## Methods for stabilizer states

### Measurement

`StabilizerState.measure(obs)` measure the stabilizer state on a set of commuting observables.

**Parameters:**
* `obs` - Observables to measure. The following types are supported:
    * `PauliList` - a list of Pauli operators (user must ensure that operators in the list are commuting, otherwise they can not measured simutaneously).
    * `StabilizerState` - stabilizers of a stabilizer state is always commuting, which can be treated as commuting observables for measurement.

**Returns:**
* `out` - measuremnt outcome, can only be $0$, $1$ for independent Pauli observables on stabilizer state, where 0 means positive (+1) eigenvalue, and 1 means negative (-1) eigenvalue.
* `log2prob` - the log2 of the probability of realizing this particular outcome.

In [30]:
state = pc.ghz_state(3)
state

StabilizerState(
   +ZZI
   +IZZ
   +XXX)

In [31]:
state.measure(pc.paulis('ZII','IZI','IIZ'))

(array([1, 1, 1]), -1.0)

In the above example, I created a GHZ state, and did single qubit Z-basis measurements on each of the qubit. We get -1 for all qubits with probility $2^{-1}=0.5$

<div class="alert alert-block alert-danger">
Measurement will <b>in place </b> change the state, as measurement will collapse the quantum state.
</div>

In [33]:
state = pc.ghz_state(3)
state.measure(pc.paulis('ZII','IZI','IIZ'))

(array([0, 0, 0]), -1.0)

In [34]:
state.measure(pc.paulis('ZII','IZI','IIZ'))

(array([0, 0, 0]), 0.0)

We see the second measurement will return the same measurement result with 100% probability

### Expectation

`StabilizerState.expect()` provide fast algorithm to evaluate expectation value of:
- Pauli operator
- Pauli Monomial/Polynomial
- Overlap between stabilizer states <font color='red'>Warning: currently it only supports pure state overlap with general stabilizer states.</font>

In [37]:
state = pc.ghz_state(5)
print("expectation values: ", state.expect(pc.paulis('XXXXX','IZIII','-ZZIII')))

expectation values:  [ 1  0 -1]


In [38]:
pauli_poly = 0.5*pc.pauli('XXXXX')+0.2j*pc.pauli('-ZZIII')
print("expectation values: ", state.expect(pauli_poly))

expectation values:  (0.5-0.2j)


### Overlap between two stabilizer states (fidelity)

In [39]:
state = pc.ghz_state(3)
state2 = pc.random_clifford_state(3)
print("State overlap is:", state.expect(state2))

State overlap is: 0.125


In [40]:
state = pc.ghz_state(3)
state2 = pc.random_clifford_state(3)
state2.set_r(1)
print("State overlap is:", state.expect(state2))

State overlap is: 0.5


### The probability of getting a bit-string readout (Bit-string probability)

`StabilizerState.get_prob(bitstring)` will return the probability of measuring given bitstring at current stabilizer state.
**Input**
- bitstring: Integer type 1D array
**Output**
- probability

In [41]:
state = pc.ghz_state(25)
print("probability of measuring 11..1 is ", state.get_prob(np.ones(25)))

probability of measuring 11..1 is  0.5


### Transform stabilzier state by rotation/Clifford transformation

As a derived class of `PauliList`, `StabilizerState` also support `StabilizerState.rotate_by(pauli)` and `StabilizerState.transform_by(clifford_map)`

In [42]:
rho = pc.ghz_state(4)

In [43]:
rho.rotate_by(pc.pauli([1,3,1,0]))

StabilizerState(
   -YIXI
   -XIYI
   -XZYZ
   +IYIX)

In [44]:
rho.transform_by(pc.random_clifford_map(4))

StabilizerState(
   -XXYZ
   -ZIXI
   +YZYI
   +XZZZ)

### Sample stabilizers from the stabilizer group

`Stabilizer.sample(L)` will sample $L$ stabilizers in the stabilizer group

In [45]:
rho = pc.ghz_state(4)
rho.sample(3)

 +ZIIZ
 -YXXY
 +IZZI

### Get density matrix of a stabilizer state

@property `StabilizerState.density_matrix` will return density matrix of stabilizer state as `PauliPolynomial`

In [5]:
pc.ghz_state(2).density_matrix

0.25 II +0.25 XX +0.25 ZZ -0.25 YY

### Calculate Entropy of a stabilizer state

`StabilizerState.entropy(subsys)` will calculate the second Renyi entropy of the stabilizer state on subregion.
**Parameter**
- `subsys`: List containing the location of region

In [48]:
state = pc.random_clifford_state(20)
print("entropy of region [1,5,10] is ", state.entropy([1,5,10]))

entropy of region [1,5,10] is  3


### Copy a stabilizer state

`StabilizerState.copy()` returns a copy of the state, such that the original state will not be touch by modification on the copy state. It is useful to copy the state for measurement (as measurement changes the state).

Example:

In [50]:
state = pc.random_clifford_state(4).copy()